### ISSUE TITLE
where is B106.01.0006.00002?

### ISSUE THREAD

**Issue by kimpham54** [dulibrarytech/digitaldu-backend#216]
i was going through the ftp and noticed that in the folder of ingested content we should have the following ingested in the repository:
/library/lib-sftp/003-ingested/B106 Anfenger Family Diaries and Material Culture/B106.01.0006.00002
i can't locate it in the frontend or backend, by doing a search for B106.01.0006.00002 so i am wondering if it got ingested, if not we would need to look into why it wasn't ingested

**Comment by freyesdulib** [comment]
It’s omission is likely due to the package being added after the ingest of the collection occurred.  It’s happened a few times with collections that were ingested early on…. The QA process mitigates this by immediately moving all packages from the ready folder at the time of ingest, so anything that is added afterwards indicates a new ingest.
